/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare namespace camel {
  export class Analyzer {
    constructor(options?: AnalyzerOptions | undefined | null)
    static create(options?: AnalyzerOptions | undefined | null): Promise<Analyzer>
    analyze(word: string): Promise<Array<ScoredAnalysis>>
    analyzeSync(word: string): Array<ScoredAnalysis>
  }
  export type JsAnalyzer = Analyzer
  export class MLEDisambiguator {
    constructor(options?: MleOptions | undefined | null)
    static create(options?: MleOptions | undefined | null): Promise<MLEDisambiguator>
    disambiguate(words: Array<string>, options?: DisambiguateOptions | undefined | null): Promise<Array<DisambiguatedWord>>
    disambiguateSync(words: Array<string>, options?: DisambiguateOptions | undefined | null): Array<DisambiguatedWord>
  }
  export type JsMleDisambiguator = MLEDisambiguator
  export class Stemmer {
    constructor(options?: StemmerOptions | undefined | null)
    static create(options?: StemmerOptions | undefined | null): Promise<Stemmer>
    stem(text: string, options?: StemOptions | undefined | null): Promise<string>
    stemSync(text: string, options?: StemOptions | undefined | null): string
    clearCache(): void
    get cacheSize(): number
  }
  export type JsStemmer = Stemmer
  export interface AnalyzerOptions {
    name?: string
    backoff?: string
    strictDigit?: boolean
    allowDownload?: boolean
  }
  export function dataDir(): string
  export function dediacAr(text: string): string
  export interface DisambiguatedWord {
    word: string
    analyses: Array<ScoredAnalysis>
  }
  export interface DisambiguateOptions {
    backoff?: string
    top?: number
  }
  export interface MleOptions {
    name?: string
    allowDownload?: boolean
  }
  export interface ScoredAnalysis {
    score: number
    category: string
    source: string
    diac: string
    lex: string
    bw: string
    gloss: string
    stem: string
    stemcat: string
    stemgloss: string
    catib6: string
    ud: string
    per: string
    asp: string
    vox: string
    mod: string
    gen: string
    num: string
    stt: string
    cas: string
    rat: string
    formGen: string
    formNum: string
    pos: string
    prc3: string
    prc2: string
    prc1: string
    prc0: string
    enc0: string
    enc1: string
    enc2: string
    d1seg: string
    d2seg: string
    d3seg: string
    atbseg: string
    d1tok: string
    d2tok: string
    d3tok: string
    atbtok: string
    bwtok: string
    root: string
    pattern: string
    caphi: string
    posLogprob: number
    lexLogprob: number
    posLexLogprob: number
  }
  export interface StemmerOptions {
    name?: string
    cacheSize?: number
    allowDownload?: boolean
  }
  export interface StemOptions {
    sep?: string
    scheme?: string
    preserveDiacritics?: boolean
    backoff?: string
    fallback?: Array<string>
  }
  export function tokenize(sentence: string, mode?: string | undefined | null): Array<string>
}

export declare namespace sina {
  export function assetUrl(key: string): string | null
  export function dataDir(): string
  export function downloadDataset(name: string): Promise<void>
  export function downloadDatasetSync(name: string): void
  export function listDatasets(): Promise<Array<string>>
  export function listDatasetsSync(): Array<string>
}
